@startuml
left to right direction
actor Usuario
rectangle "Front-end Adivinanzas Matemáticas con React Native" {
 Usuario -- (Seleccionar Nivel)
 Usuario -- (Visualizar Adivinanza)
 Usuario -- (Enviar Respuesta)
 Usuario <.. (Recibir Feedback) : extends
 Usuario -- (Ver Progreso y Recompensas)
}
@enduml