@startuml Diagrama entidad relación

entity Tema {
    +id: int
    +tema: string
}

entity Subtema {
    +name: string
}

entity Adivinanza {
    +id: int
    +pregunta: string
    +respuesta: string
}

Tema ||--o Subtema : tiene
Subtema ||--o Adivinanza : tiene

@enduml
